# LA-8 Inverse of matrix

In [10]:
#### import numpy as np
k=3
a = np.zeros((k,k),dtype = int)
print("enter {0} elements".format(k*k))
for i in range(k):
    for j in range(k):
        a[i][j]=input()
print(a)
print("inverse of the matrix=\n",a.T/np.linalg.det(a))

enter 9 elements
1
2
3
4
5
67
7
8
9
[[ 1  2  3]
 [ 4  5 67]
 [ 7  8  9]]
inverse of the matrix=
 [[0.00273224 0.01092896 0.01912568]
 [0.00546448 0.0136612  0.02185792]
 [0.00819672 0.18306011 0.02459016]]


# LA-7 Number of occurences

In [3]:
f=open('LotsOFWords.txt', 'r')
n=0
for l in f:
    w = l.split()
    for i in range(len(w)):
        if (w[i]=='apple' or w[i]=='apple.' or w[i]=='apple?'):
            n=n+1
print(n)

29


# LA6 Prime no.s between 0 to 100

In [2]:
[num for num in range(2,1000) if 0 not in [num%i for i in range(2,num)]]


[2,
 3,
 5,
 7,
 11,
 13,
 17,
 19,
 23,
 29,
 31,
 37,
 41,
 43,
 47,
 53,
 59,
 61,
 67,
 71,
 73,
 79,
 83,
 89,
 97,
 101,
 103,
 107,
 109,
 113,
 127,
 131,
 137,
 139,
 149,
 151,
 157,
 163,
 167,
 173,
 179,
 181,
 191,
 193,
 197,
 199,
 211,
 223,
 227,
 229,
 233,
 239,
 241,
 251,
 257,
 263,
 269,
 271,
 277,
 281,
 283,
 293,
 307,
 311,
 313,
 317,
 331,
 337,
 347,
 349,
 353,
 359,
 367,
 373,
 379,
 383,
 389,
 397,
 401,
 409,
 419,
 421,
 431,
 433,
 439,
 443,
 449,
 457,
 461,
 463,
 467,
 479,
 487,
 491,
 499,
 503,
 509,
 521,
 523,
 541,
 547,
 557,
 563,
 569,
 571,
 577,
 587,
 593,
 599,
 601,
 607,
 613,
 617,
 619,
 631,
 641,
 643,
 647,
 653,
 659,
 661,
 673,
 677,
 683,
 691,
 701,
 709,
 719,
 727,
 733,
 739,
 743,
 751,
 757,
 761,
 769,
 773,
 787,
 797,
 809,
 811,
 821,
 823,
 827,
 829,
 839,
 853,
 857,
 859,
 863,
 877,
 881,
 883,
 887,
 907,
 911,
 919,
 929,
 937,
 941,
 947,
 953,
 967,
 971,
 977,
 983,
 991,
 997]

In [93]:

for num in range(2,101):
    s = -1
    for i in range(2,num):
        if num % i == 0:
                s = 0
    if s==-1:
            print(num)

2
3
5
7
11
13
17
19
23
29
31
37
41
43
47
53
59
61
67
71
73
79
83
89
97


# LA-9 Distance between two points

In [2]:
import numpy as np
a = np.zeros((1,2),dtype = int)
print("enter 2 elements")
for i in range(1):
    for j in range(2):
        a[i][j]=int(input())
#a=a.ravel()
b = np.zeros((1,2),dtype = int)
print("enter 2 elements")
for i in range(1):
    for j in range(2):
        b[i][j]=int(input())
#b=b.ravel()
sq1=pow((a[0:2,0]-b[0:2,0]),2)
sq2=pow((a[0:2,1]-b[0:2,1]),2)
sq=pow((sq1+sq2),1/2)
print(sq)

enter 2 elements
1
2
enter 2 elements
1
2
[0.]
