# Numpy(Numerical Python)

In [2]:
#conda install numpy
#pip install numpy

In [7]:
import numpy as np
np.__version__

'1.17.3'

In [30]:
import numpy as np
a = np.array([1,2,3,4])
print(type(a))#numpy.ndarray(n dimensional array)
print(a)
print(a.shape)#to fine the size of the array

<class 'numpy.ndarray'>
[1 2 3 4]
(4,)


In [32]:
import numpy as np
a = np.array([[1,2,3,4],[2,4,5,6],[1,334,5,53]])
print(type(a))#numpy.ndarray(n dimensional array)
print(a)
print(a.shape)
print(a[2][3])

<class 'numpy.ndarray'>
[[  1   2   3   4]
 [  2   4   5   6]
 [  1 334   5  53]]
(3, 4)
53


# List to numpy

In [36]:
l1=[1,2,3,4]
l2=[[2,5,67,4],[31,513,512,4]]
n= np.array(l1)
n= np.array(l2)
print(n)
print(n[0])

[[  2   5  67   4]
 [ 31 513 512   4]]
[ 2  5 67  4]


# Tuple to numpy

In [44]:
l1=(1,2,3,4)
l2=((2,5,67,4),(31,513,512,4))
n= np.array(l1)
n= np.array(l2)
print(n)
print(n.shape)
print(n[1])
print(type(n))

[[  2   5  67   4]
 [ 31 513 512   4]]
(2, 4)
[ 31 513 512   4]
<class 'numpy.ndarray'>


# Reshape Funtion

In [74]:
l1=[1,2,3,4,56,7,8,9,3,0]
a=np.array(l1)
print(a)
b=a.reshape(2,5)
print(b,'\n')
print(a.reshape(-3,2),'\n')
print(a.reshape(10,1),'\n')# when we reshape 1d array it turns into 2d dimensional array with [[_,_][_,_]]

[ 1  2  3  4 56  7  8  9  3  0]
[[ 1  2  3  4 56]
 [ 7  8  9  3  0]] 

[[ 1  2]
 [ 3  4]
 [56  7]
 [ 8  9]
 [ 3  0]] 

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [56]
 [ 7]
 [ 8]
 [ 9]
 [ 3]
 [ 0]] 



# Arange Function

In [ ]:
np.arange(start,end,step)

In [65]:
z= np.arange(2,10,0.5)
print(z)
print(type(z))

[2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]
<class 'numpy.ndarray'>


In [67]:
x=np.arange(8)
print(x)
print(x.reshape(-1,4))

[0 1 2 3 4 5 6 7]
[[0 1 2 3]
 [4 5 6 7]]


In [73]:
x=np.arange(8).reshape(-1,2)
print(x)
print(type(x))

[[0 1]
 [2 3]
 [4 5]
 [6 7]]
<class 'numpy.ndarray'>


In [67]:
x=np.arange(8)
print(x)
print(x.reshape(-1,4))

[0 1 2 3 4 5 6 7]
[[0 1 2 3]
 [4 5 6 7]]


# Ravel Function

In [35]:
x=np.arange(8).reshape(-1,2)#flatens the array
print(x)
print(x.ravel())#[0 1 2 3 4 5 6 7]
print(x.ravel(2))#[0 4 1 5 2 6 3 7]


[[0 1]
 [2 3]
 [4 5]
 [6 7]]
[0 1 2 3 4 5 6 7]
[0 2 4 6 1 3 5 7]


D:\anaconda\lib\site-packages\ipykernel_launcher.py:4: DeprecationWarning: Non-string object detected for the array ordering. Please pass in 'C', 'F', 'A', or 'K' instead
  after removing the cwd from sys.path.


# Lab assignment(multiplication of matrices)

In [115]:
a=np.array([[1,2,2],[3,4,4],[3,6,3]])
b=np.array([[1,2,3],[1,2,5],[4,5,7]])
for i in range(3):
    for j in range(3):
        c[i][j]=0
        for k in range(3):
            c[i][j]+=a[i][k]*b[k][j]
print(c)
    

[[11 16 27]
 [23 34 57]
 [21 33 60]]


# Data type conversion

In [119]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]],dtype = str)
print(a)

[['1' '2' '3']
 ['4' '5' '6']
 ['7' '8' '9']]


In [120]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]],dtype = float)
print(b)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [128]:
c = np.array([[1.2,2,3],[4,5,6],[7,8,9]],dtype = complex)
print(c)
print(type(c[0,0]))

[[1.2+0.j 2. +0.j 3. +0.j]
 [4. +0.j 5. +0.j 6. +0.j]
 [7. +0.j 8. +0.j 9. +0.j]]
<class 'numpy.complex128'>


# Functions in matrices

In [132]:
#create an array of all zeros
d = np.zeros((3,3))
print(d)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [133]:
d1 = np.zeros((3,3),dtype = int)
print(d1)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [134]:
d2 = np.ones((3,3),dtype = int)
print(d2)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [138]:
d3 = np.full((4,10),'5.8')
print(d3)

[['5.8' '5.8' '5.8' '5.8' '5.8' '5.8' '5.8' '5.8' '5.8' '5.8']
 ['5.8' '5.8' '5.8' '5.8' '5.8' '5.8' '5.8' '5.8' '5.8' '5.8']
 ['5.8' '5.8' '5.8' '5.8' '5.8' '5.8' '5.8' '5.8' '5.8' '5.8']
 ['5.8' '5.8' '5.8' '5.8' '5.8' '5.8' '5.8' '5.8' '5.8' '5.8']]


In [142]:
d = np.eye(4,dtype = int)
print(d)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [164]:
d=np.random.randint(1.1,20.2,size=(3,9))
print(d)

[[ 9 13 18 18  8  4  4 16 18]
 [ 3  5  1 18 19  8 18 13  8]
 [ 9 17 14 11  3 17 17 19 12]]


# Lab Assignment

In [177]:
d1 = np.zeros((4,3),dtype = int)
print(d1)
d2 = np.ones((4,3),dtype = int)
print(d2)
d3 = np.full((4,3),4.+0.4j)
print(d3)
print(type(d3[0,0]))

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
[[4.+0.4j 4.+0.4j 4.+0.4j]
 [4.+0.4j 4.+0.4j 4.+0.4j]
 [4.+0.4j 4.+0.4j 4.+0.4j]
 [4.+0.4j 4.+0.4j 4.+0.4j]]
<class 'numpy.complex128'>


# Array Indexing

## Positive Indexing

In [243]:
import numpy as np
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)
b=a[-2:-1,-4:-2]
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[5 6]]


In [195]:
import numpy as np
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)
b=a[:-2,:-1]
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[1 2 3]]


In [260]:
import numpy as np
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)
b=a[-1:,(-1,-4)]
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[12  9]]


In [ ]:
import numpy as np
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)
b=a[-1:,::2]
print(b)

In [254]:
import numpy as np
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)
b=a[1:2,::2]
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[5 7]]


In [274]:
b = np.array([[1,2,3],[5,6,7],[9,10,11],[12,13,14]])
print(b)
d=b[:2,1:3]
print(d)

d[0,0]=77
print("d=",d)

print(b)

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [12 13 14]]
[[2 3]
 [6 7]]
d= [[77  3]
 [ 6  7]]
[[ 1 77  3]
 [ 5  6  7]
 [ 9 10 11]
 [12 13 14]]


# Lab Assignment

In [2]:
import numpy as np
a = np.zeros((3,4),dtype = int)
print("enter 12 elements")
for i in range(3):
    for j in range(4):
        a[i][j]=input()
print(a)
print('shape=',a.shape)
print('2nd row=',a[1:2,:])
print('after adding 10 to 1st row elements')
for j in range(4):
    a[0][j]+=10
print(a)

enter 12 elements
1
2
34
556
6
3
24
5
1345
1
45
135
[[   1    2   34  556]
 [   6    3   24    5]
 [1345    1   45  135]]
shape= (3, 4)
2nd row= [[ 6  3 24  5]]
after adding 10 to 1st row elements
[[  11   12   44  566]
 [   6    3   24    5]
 [1345    1   45  135]]


# Advanced Indexing

In [8]:
b = np.array([[1,2,3,5],[5,6,7,6],[9,10,11,3]])
print(b)
b[0::2,[0,3]]

[[ 1  2  3  5]
 [ 5  6  7  6]
 [ 9 10 11  3]]


array([[1, 5],
       [9, 3]])

# Boolean Indexing

In [19]:
x=np.array([[0,1,34],[3,4,2],[6,7,8],[9,10,11]])
print(x)
y=x>5
print("\n",y)
z=x[x>5]#we use this in Pandas
print('\n',z)

[[ 0  1 34]
 [ 3  4  2]
 [ 6  7  8]
 [ 9 10 11]]

 [[False False  True]
 [False False False]
 [ True  True  True]
 [ True  True  True]]

 [34  6  7  8  9 10 11]


# Array Math

In [32]:
x=np.array([[1,2,],[3,4]])
y=np.array([[5,6,],[7,8]])
print(x)
print(y,"\n")
print(x+y)
print(np.add(x,y),"\n")
print(x-y)
print(np.subtract(x,y),"\n")
print(x*y)
print(np.multiply(x,y),"\n")    
print(x/y)
print(np.divide(x,y),"\n")

[[1 2]
 [3 4]]
[[5 6]
 [7 8]] 

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]] 

[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]] 

[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]] 

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]] 



In [33]:
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


# Transpose of a matrix

In [34]:
print(x.T)

[[1 3]
 [2 4]]


In [43]:
x=np.array([[1,2,],[3,4]])
print(int(np.linalg.det(x)))

-2
